
#jdbc.url=postgresql://localhost:5312/WeGoOurTrip
#jdbc.username=WeGoOurTrip
#jdbc.password=rlawnstjq1!
#jdbc.driverClassName=org.postgresql.Driver

jdbc.url=jdbc:postgresql://localhost:5312/WeGoOurTrip
jdbc.username=WeGoOurTrip
jdbc.password=rlawnstjq1!
jdbc.driverClassName=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
#spring.datasource.username=kjs
#spring.datasource.password=rlawnstjq1!
#spring.datasource.driver-class-name=org.postgresql.Driver

#busStop.url=https://apis.data.go.kr/6300000/GetStatListService/getStatList
#busStop.key=FAOVd%2FY34UlV3eqkp%2BRhfuZSTDBBL%2FGXxG6zqK5hnZZm%2BMcvDOg7QkWyINi%2FwuJjkSqSNFkP8jd4hljWOCxK0A%3D%3D
#
#busStopArive.url=http://openapitraffic.daejeon.go.kr/api/rest/arrive/getArrInfoByUid
#
##Bus Locate
#busLocate.url=http://openapitraffic.daejeon.go.kr/api/rest/busposinfo/getBusPosByRtid
#
##Bus Route
#busRoute.url=http://openapitraffic.daejeon.go.kr/api/rest/busRouteInfo/getStaionByRoute
#
##Bus Info
#busInfo.url=http://openapitraffic.daejeon.go.kr/api/rest/busRouteInfo/getRouteInfoAll
#
##JWT secret Key
#jwt.secret = rlawnstjqdmlCnldjqehwjsrldladjswpCNLdjqGkfwlAhfmRPtdmann941224
#
## Access Token \uB9CC\uB8CC \uC2DC\uAC04 (\uC608: 30\uBD84, 1800000ms, 30min)
##jwt.access-token-expiration-time=1800000
#jwt.access-token-expiration-time=310000
#
## Refresh Token \uB9CC\uB8CC \uC2DC\uAC04 (\uC608: 7\uC77C, 604800000ms)
#jwt.refresh-token-expiration-time=604800000